##Import Libraries

In [ ]:
import pandas as pd
import numpy as np

## Data load

In [ ]:
df = pd.read_csv('/content/drive/My Drive/machine learning/classification/data/Human_Resources_Employee_Attrition.csv')
df.describe()

       satisfaction_level  last_evaluation  ...          left  promotion_last_5years
count        14999.000000     14999.000000  ...  14999.000000           14999.000000
mean             0.612834         0.716102  ...      0.238083               0.021268
std              0.248631         0.171169  ...      0.425924               0.144281
min              0.090000         0.360000  ...      0.000000               0.000000
25%              0.440000         0.560000  ...      0.000000               0.000000
50%              0.640000         0.720000  ...      0.000000               0.000000
75%              0.820000         0.870000  ...      0.000000               0.000000
max              1.000000         1.000000  ...      1.000000               1.000000

[8 rows x 8 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   satisfaction_level     14999 non-null  float64
 1   last_evaluation        14999 non-null  float64
 2   number_of_projects     14999 non-null  int64
 3   average_monthly_hours  14999 non-null  int64
 4   years_at_company       14999 non-null  int64
 5   work_accident          14999 non-null  int64
 6   left                   14999 non-null  int64
 7   promotion_last_5years  14999 non-null  int64
 8   department             14999 non-null  object
 9   salary                 14999 non-null  object
dtypes: float64(2), int64(6), object(2)
memory usage: 1.1+ MB

In [ ]:
df.salary.unique()

array(['low', 'medium', 'high'], dtype=object)

In [ ]:
df.salary.unique()

array(['low', 'medium', 'high'], dtype=object)

In [ ]:
df.salary.value_counts(ascending=False)

low       7316
medium    6446
high      1237
Name: salary, dtype: int64

In [ ]:
df.department.unique()

array(['sales', 'accounting', 'hr', 'technical', 'support', 'management',
       'IT', 'product_mng', 'marketing', 'RandD'], dtype=object)

In [ ]:
df.department.value_counts()

sales          4140
technical      2720
support        2229
IT             1227
product_mng     902
marketing       858
RandD           787
accounting      767
hr              739
management      630
Name: department, dtype: int64

In [ ]:
df1 = df.copy()

## we have to change the categorcial data  into num data

### LabelEncoder

In [ ]:
# in the target column we apply Lablencoding
# feature column we use OneHotEncoding

In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [ ]:
df1.iloc[:,9] = encoder.fit_transform(df1.iloc[:,9])

In [ ]:
df1.head()

   satisfaction_level  last_evaluation  ...  department  salary
0                0.38             0.53  ...       sales       1
1                0.80             0.86  ...       sales       2
2                0.11             0.88  ...       sales       2
3                0.72             0.87  ...       sales       1
4                0.37             0.52  ...       sales       1

[5 rows x 10 columns]

In [ ]:
df.head()

   satisfaction_level  last_evaluation  ...  department  salary
0                0.38             0.53  ...       sales     low
1                0.80             0.86  ...       sales  medium
2                0.11             0.88  ...       sales  medium
3                0.72             0.87  ...       sales     low
4                0.37             0.52  ...       sales     low

[5 rows x 10 columns]

In [ ]:
df1.salary.unique()

array([1, 2, 0])

In [ ]:
encoder.classes_
# high 0 ,low 1 ,medium 2

array(['high', 'low', 'medium'], dtype=object)

In [ ]:
df.shape

(14999, 10)

###OneHotEncoding

In [ ]:
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder(dtype='int64')

In [ ]:
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers = [('encoding',onehotencoder,[8])],remainder = 'passthrough')

In [ ]:
df2 = ct.fit_transform(df1.iloc[:,:9])

In [ ]:
df2.shape

(14999, 18)

In [ ]:
df2.dtype

dtype('float64')

In [ ]:
df2

array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [ ]:
df2[1]

array([  0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   1.  ,
         0.  ,   0.  ,   0.8 ,   0.86,   5.  , 262.  ,   6.  ,   0.  ,
         1.  ,   0.  ])

In [ ]:
df2 = pd.DataFrame(df2)

In [ ]:
df2.head()

    0    1    2    3    4    5    6   ...    11   12     13   14   15   16   17
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.53  2.0  157.0  3.0  0.0  1.0  0.0
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.86  5.0  262.0  6.0  0.0  1.0  0.0
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.88  7.0  272.0  4.0  0.0  1.0  0.0
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.87  5.0  223.0  5.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.52  2.0  159.0  3.0  0.0  1.0  0.0

[5 rows x 18 columns]

In [ ]:
df2.head()

    0    1    2    3    4    5    6   ...    11   12     13   14   15   16   17
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.53  2.0  157.0  3.0  0.0  1.0  0.0
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.86  5.0  262.0  6.0  0.0  1.0  0.0
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.88  7.0  272.0  4.0  0.0  1.0  0.0
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.87  5.0  223.0  5.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.52  2.0  159.0  3.0  0.0  1.0  0.0

[5 rows x 18 columns]

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 18 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       14999 non-null  float64
 1   1       14999 non-null  float64
 2   2       14999 non-null  float64
 3   3       14999 non-null  float64
 4   4       14999 non-null  float64
 5   5       14999 non-null  float64
 6   6       14999 non-null  float64
 7   7       14999 non-null  float64
 8   8       14999 non-null  float64
 9   9       14999 non-null  float64
 10  10      14999 non-null  float64
 11  11      14999 non-null  float64
 12  12      14999 non-null  float64
 13  13      14999 non-null  float64
 14  14      14999 non-null  float64
 15  15      14999 non-null  float64
 16  16      14999 non-null  float64
 17  17      14999 non-null  float64
dtypes: float64(18)
memory usage: 2.1 MB

## feature and target

In [ ]:
X = df2.iloc[:,:].values
y = df1['salary'].values

In [ ]:
X.shape,y.shape

((14999, 18), (14999,))

## train test split data

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

##Model

In [ ]:
from sklearn.